export const USER_DATA_ON_CHANGE_FIELD = 'USER_DATA_ON_CHANGE_FIELD';
export const SPINNER_SET_LOADING_VALUE = 'SPINNER_SET_LOADING_VALUE';
export const APPLICATION_SET_TOAST = 'APPLICATION_SET_TOAST';
